### ISSUE TITLE
add topics

### ISSUE THREAD

**Issue by Beliavsky** [crobertocamilo/MD-permeation#1]
I suggest adding topics such as `molecular-dynamics` in the About section at https://github.com/crobertocamilo/MD-permeation.

**Comment by crobertocamilo** [comment]
Dear Beliavsky,

I appreciate the suggestion. Thank you!

Regards,
Carlos R S Camilo.


Em sex., 25 de fev. de 2022 às 09:45, Beliavsky ***@***.***>
escreveu:

**Comment by crobertocamilo** [comment]
Topics added.
